### ISSUE TITLE
clash排除应用-clash国内代理-clash跑车机场

### ISSUE THREAD

**Issue by clashvpn8** [clashvpn8/p#10]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/#/register?code=MIGgsNCV
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
永久海外官网：（翻墙才能打开）https://www.iovevpn.com/
爱连VPN客户端和APP下载地址：（支持安卓-Winodws-MAC-苹果ios）https://www.ailianvpn.com/
飞机爱连VPN官方频道通知群 https://t.me/iovevpn1
有任何问题反馈永久海外邮箱：ailianvpn@gmail.com
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

推荐榜单2、火火VPN
注册登陆网址：（打不开请点击下面导航）https://www.huohuovpn.com/#/register?code=VbaZhlak
永久导航：（最新网址进导航页面查找）https://www.huohuohuo.cloud/
永久海外官网：（翻墙才能打开）https://www.huohuovpn.com
火火加速器上線啦，高科技翻墻上網，帶你看看外面的世界 火火加速器上線啦，高科技翻墻上網，帶你看看外面的世界 網址總死總找不到，播放不了，大陸封鎖網址 ，沒關系可以用我們的高科技上網軟件，軟件使用全程SSL加密,保護你的隱私安全

#### 一、Clash 排除应用

**Clash 排除应用** 指的是设置 Clash 以便特定应用程序绕过代理，直接使用本地网络。以下是如何配置 Clash 排除应用的步骤：

1. **编辑配置文件**：
   - **打开配置文件**：编辑 Clash 的配置文件，通常是 `config.yaml`。

2. **配置排除规则**：
   - **使用 `bypass` 规则**：你可以设置规则让特定应用的流量不通过代理。
   - **示例配置**：
     ```yaml
     rules:
       - DOMAIN-SUFFIX,example.com,DIRECT
       - IP-CIDR,192.168.1.0/24,DIRECT
       - PROCESS-NAME,appname.exe,DIRECT
       - MATCH,Proxy
     ```
     在这里：
     - `DOMAIN-SUFFIX,example.com,DIRECT`：所有以 `example.com` 结尾的域名使用直接连接。
     - `IP-CIDR,192.168.1.0/24,DIRECT`：所有指定的 IP 地址范围直接连接。
     - `PROCESS-NAME,appname.exe,DIRECT`：指定的进程名称（如 `appname.exe`）绕过代理。

3. **保存和应用配置**：
   - **保存文件**：保存修改后的 `config.yaml` 文件。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用，以使更改生效。

4. **验证设置**：
   - **测试应用**：确保排除的应用按照配置直接连接到互联网。

#### 二、Clash 国内代理

**Clash 国内代理** 指的是将国内流量通过代理进行处理，以突破网络限制或提高访问速度。以下是如何配置国内代理的步骤：

1. **获取国内代理节点**：
   - **购买或获取节点**：从国内服务提供商获取国内代理节点的配置。

2. **编辑配置文件**：
   - **添加国内节点**：将国内代理节点信息添加到 `proxies` 部分。
     ```yaml
     proxies:
       - name: "DomesticNode"
         type: socks5
         server: "domestic.example.com"
         port: 1080
         password: "your-password"
         method: "aes-256-gcm"
     ```
   - **设置国内流量规则**：将国内流量指向该代理节点。
     ```yaml
     proxy-groups:
       - name: "Domestic"
         type: select
         proxies:
           - "DomesticNode"
           - "AnotherNode"
     
     rules:
       - DOMAIN-SUFFIX,cn,Domestic
       - MATCH,Proxy
     ```

3. **保存和应用配置**：
   - **保存文件**：保存修改后的配置文件。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用。

4. **验证效果**：
   - **测试国内访问**：访问国内网站，确保流量通过指定的国内代理。

#### 三、Clash 跑车机场

**Clash 跑车机场** 可能指的是高性能的代理服务提供商（即“机场”）或节点，通常提供更快的速度和更高的稳定性。以下是如何设置和使用这些节点：

1. **选择跑车机场**：
   - **购买服务**：选择提供高性能节点的服务提供商，并购买相应的套餐。
   - **示例提供商**：如 [跑车机场](https://example.com)（请确保选择可靠的提供商）。

2. **获取节点信息**：
   - **下载配置文件**：从跑车机场获取节点配置文件或连接信息。

3. **编辑 Clash 配置文件**：
   - **添加节点**：将跑车机场提供的节点信息添加到 `proxies` 部分。
     ```yaml
     proxies:
       - name: "SuperFastNode"
         type: socks5
         server: "superfast.example.com"
         port: 1080
         password: "your-password"
         method: "aes-256-gcm"
     ```
   - **配置代理组**：在 `proxy-groups` 中设置默认使用跑车节点。
     ```yaml
     proxy-groups:
       - name: "Fastest"
         type: url-test
         proxies:
           - "SuperFastNode"
           - "AnotherNode"
         url: "http://www.gstatic.com/generate_204"
         interval: 300
     ```

4. **保存和应用配置**：
   - **保存文件**：保存配置文件的更改。
   - **重新加载配置**：在 Clash 客户端中重新加载配置或重启应用。

5. **验证性能**：
   - **测试速度**：访问一些需要快速网络的服务或网站，以确认跑车机场节点的性能。

通过这些步骤，你可以有效地配置 Clash 以排除特定应用，使用国内代理来优化网络访问，并利用跑车机场的高性能节点提升网络速度。
